[project]
src = "src"

[networks.contracts.price_feed] #this checks if the contract has a contract address if not it deployed a local one 
deployer_script = "script/deploy_mocks.py"



[networks.sepolia]
url = "$SAPOLIA_RPC_URL"
save_to_db = false
default_account_name = "scofield"
prompt_live = false
explorar_url = "https://eth-sepolia.blockscout.com/"
explorar_type = "blockscout"

[networks.pyevm.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"


[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
deployer_script = "deploy_mocks.py"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
